services:
  - type: web
    name: bookclub
    env: docker
    repo: https://github.com/yourusername/bookclub
    branch: main
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
    runtime: docker
